#!/bin/sh

set -eu

DAYS_PRIOR="${1:-10}" # TODO: ensure > 0
export DAYS_PRIOR
TOKENSFILE="${2:-./tokens}"
export TOKENSFILE

main() {
	load
	{ transform || return 1; } | compile
}

load() {
	set -a
	# shellcheck disable=SC1090
	. "$TOKENSFILE" || return 1
	set +a

	cached_pipe accounts
	# shellcheck disable=SC2064
	trap "rm '$(get_pipe accounts)'" EXIT
	cached_pipe transactions "${DAYS_PRIOR}"
	# shellcheck disable=SC2064
	trap "rm '$(get_pipe accounts)' '$(get_pipe transactions)'" EXIT
}
transactions() {
	dates=$(jq -nf date.jq) || return 1
	START=$(echo "$dates" | jq -r .start)
	export START
	END=$(echo "$dates" | jq -r .end)
	export END

	initial_response=$(curl -K get-initial-transactions.curl) || return 1
	iterate_transactions "${initial_response}"
}
iterate_transactions() {
        echo "$1" | jq '.items.[]' || return 1
	CURSOR=$(cursor "$1") || return 1
        export CURSOR
        [ "${CURSOR}" = null ] && return 0

        successive_response=$(curl -K get-initial-transactions.curl \
                              -K cursor.curl) || return 1
        iterate_transactions "${successive_response}" || return 1
}
cursor() {
	jq -n -r --argjson response "$1" '$response.cursor.next'
}

accounts() {
	curl -K get-accounts.curl | jq -f account-format.jq
}


transform() {
	jq -f transform.jq --argjson accounts "$(cat "$(get_pipe accounts)")" <"$(get_pipe transactions)"
}

compile() {
	jq -fr compile.jq
}

cached_pipe() {
	command="$1"
	cachefile="$(get_cachefile "${command}")" || return 1
	pipe="$(get_pipe "${command}")" || return 1
	mkfifo "$pipe"
	if [ -f "$cachefile" ]; then
		cat "$cachefile"
	else 
		{ ${command} || return 1; } | tee "${cachefile}"
	fi >"$pipe" &
}
get_pipe() {
	echo "$1-pipe"
}
get_cachefile() {
	command_as_file="$(echo "${1}" | sed 's/ /-/')" || return 1
	echo "$(date +%Y-%m-%d)-${command_as_file}.json.data"

}

main
